In [7]:
import statistics

In [8]:
P = [2, 4, 4, 4, 5, 5, 7, 9]

In [9]:
statistics.mean(P)

5

In [10]:
import numpy as np

In [11]:
Q = [2, 4, 4, 4, 5, 5, 7, 9]
np.mean(Q)

5.0

In [12]:
np.std(Q)

2.0

In [14]:
np.percentile(P,50)

4.5

In [15]:
np.var(Q)

4.0

In [16]:
np.var(P)

4.0

In [17]:
np.cov(P,Q)

array([[4.57142857, 4.57142857],
       [4.57142857, 4.57142857]])

In [18]:
A = [2, 4, 4, 4, 5, 5, 7, 9]
B = [10, 13, 15, 14, 13, 16, 18, 21]

In [19]:
np.cov(A, B)

array([[ 4.57142857,  6.85714286],
       [ 6.85714286, 11.42857143]])

In [20]:
np.corrcoef(A, B)

array([[1.       , 0.9486833],
       [0.9486833, 1.       ]])